Add editorconfig-checker lint

diff --git a/tests/scripts/run_cargo_tests b/tests/scripts/run_cargo_tests
--- a/tests/scripts/run_cargo_tests
+++ b/tests/scripts/run_cargo_tests
@@ -3,20 +3,20 @@
 set -eux
 
 if [[ "$#" -ne 1 ]]; then
-  echo "Usage: $0 <crate_type>" >&2
-  exit 1
+    echo "Usage: $0 <crate_type>" >&2
+    exit 1
 fi
 
 crate_type="$1"
 case "${crate_type}" in
 bin | lib) ;;
 *)
-  echo "Invalid crate_type: ${crate_type}" >&2
-  exit 1
-  ;;
+    echo "Invalid crate_type: ${crate_type}" >&2
+    exit 1
+    ;;
 esac
 
 just ci
 if [[ "${crate_type}" == "bin" ]]; then
-  ./scripts/build-dist
+    ./scripts/build-dist
 fi
